server:
  port: 8080

spring:
  application:
    name: pedidos360-backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pedidos360
    username: pedidos_user
    password: Pedidos123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/4ecc8427-8a7b-46cc-aab9-4f000ea95b2e/
          audiences: api://d58f7e12-14df-458c-b966-507316adb29c